name: Docker Image CI

on:
  push:
    branches:
      - spleeter*
      - whisper*
      - allinone
      - master

env:
  IMAGE_NAME: orpheus
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: checkout Repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Github
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true

      - name: Build spleeter branch Docker image
        uses: docker/build-push-action@v4
        if: ${{ env.BRANCH_NAME == 'spleeter' }}
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          target: spleeter
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:spleeter
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:spleeter

      - name: Build whisper-base branch Docker image
        uses: docker/build-push-action@v4
        if: ${{ env.BRANCH_NAME == 'whisper-base' }}
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          target: whisper-base
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:whisper-base
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:whisper-base

      - name: Build whisper-medium branch Docker image
        uses: docker/build-push-action@v4
        if: ${{ env.BRANCH_NAME == 'whisper-medium' }}
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          target: whisper-medium
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:whisper-medium
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:whisper-medium

      - name: Build whisper-large branch Docker image
        uses: docker/build-push-action@v4
        if: ${{ env.BRANCH_NAME == 'whisper-large' }}
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          target: whisper-large
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:whisper-large
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:whisper-large

      - name: Build whisper-all branch Docker image
        # whisper include both medium and large models
        uses: docker/build-push-action@v4
        if: ${{ env.BRANCH_NAME == 'whisper-all' }}
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          target: whisper-all
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:whisper-all
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:whisper-all

      - name: Build spleeter-whisper-medium branch Docker image
        uses: docker/build-push-action@v4
        if: ${{ env.BRANCH_NAME == 'spleeter-whisper-medium' }}
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          target: spleeter-whisper-medium
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:spleeter-whisper-medium
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:spleeter-whisper-medium

      - name: Build spleeter-whisper-large branch Docker image
        uses: docker/build-push-action@v4
        if: ${{ env.BRANCH_NAME == 'spleeter-whisper-large' }}
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          target: spleeter-whisper-large
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:spleeter-whisper-large
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:spleeter-whisper-large

      - name: Build allinone branch Docker image
        uses: docker/build-push-action@v4
        if: ${{ env.BRANCH_NAME == 'allinone' }}
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          target: allinone
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:allinone
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:allinone

      - name: Build ${{ env.IMAGE_NAME }}:v2ok branch Docker image
        uses: docker/build-push-action@v4
        if: ${{ env.BRANCH_NAME == 'master' }}
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          target: v2ok
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:v2ok
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:v2ok

      - name: Build ${{ env.IMAGE_NAME }}:y2ok branch Docker image
        uses: docker/build-push-action@v4
        if: ${{ env.BRANCH_NAME == 'master' }}
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          target: y2ok
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:y2ok
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:y2ok