name: Docker Image CI

on:
  push:
    branches:
      - spleeter
      - whisper-base
      - whisper-medium
      - whisper-large
      - whisper-all
      - spleeter-whisper-medium
      - spleeter-whisper-large
      - allinone
      - v2ok
      - y2ok
      - youtube

env:
  IMAGE_NAME: orpheus
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build-and-push-image:
#    if: ${{ env.BRANCH_NAME != 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout Repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Github
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true

      - name: Build ${{ env.BRANCH_NAME }} tag of Docker image
        # build docker image tag with branch name
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          target: ${{ env.BRANCH_NAME }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}
